# Generated by Django 6.0.6 on 2026-06-25 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_ruta_activa_ruta_conductor_ruta_lat_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor_nombre', models.CharField(max_length=120)),
                ('conductor_licencia', models.CharField(blank=True, max_length=60)),
                ('conductor_cedula', models.CharField(blank=True, max_length=30)),
                ('placa', models.CharField(max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('origen', models.CharField(max_length=150)),
                ('destino', models.CharField(max_length=150)),
                ('km_recorridos', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_carga', models.CharField(blank=True, max_length=120)),
                ('recursos', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('total_operativo', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_adicional', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_viaje', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('Peaje', 'Peaje'), ('Combustible', 'Combustible'), ('Manifiesto de carga', 'Manifiesto de carga'), ('Hospedaje', 'Hospedaje'), ('Almuerzo', 'Almuerzo'), ('Desayuno', 'Desayuno'), ('Cena', 'Cena'), ('Servicio mecánico', 'Servicio mecánico'), ('Otro', 'Otro')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='tareas.viaje')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='evidencias/')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='tareas.viaje')),
            ],
        ),
    ]
