# Generated by Django 6.0.2 on 2026-06-26 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_viaje_gastoviaje_evidenciaviaje'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('cedula', models.CharField(max_length=30, unique=True)),
                ('licencia', models.CharField(max_length=60)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('en_ruta', 'En ruta'), ('suspendido', 'Suspendido')], default='activo', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='conductores/')),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ruta',
            name='creada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
