# Generated by Django 6.0.6 on 2026-07-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_merge_20260630_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UbicacionConductor',
        ),
    ]
